# Generated by Django 5.1.5 on 2025-03-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "participants",
            "0027_alter_tournamentinstitution_adjudicators_allocated_and_more",
        ),
        ("registration", "0001_initial"),
        ("tournaments", "0013_scheduleevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_key", models.CharField(max_length=50, verbose_name="URL key")),
                (
                    "created_on",
                    models.DateTimeField(auto_now=True, verbose_name="created on"),
                ),
                ("revoked", models.BooleanField(default=False, verbose_name="revoked")),
                (
                    "for_content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label", "participants"), ("model", "speaker")
                            ),
                            models.Q(
                                ("app_label", "participants"), ("model", "adjudicator")
                            ),
                            models.Q(("app_label", "participants"), ("model", "team")),
                            models.Q(
                                ("app_label", "participants"), ("model", "institution")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="for content type",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.team",
                        verbose_name="team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                        verbose_name="tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
    ]
